"""Core incident analysis workflow.

This module keeps notebook/UI code thin: gather incident context, build a
grounded prompt, and call the configured LLM.
"""

from __future__ import annotations  # Keep modern type hints working across supported Python versions.

import base64  # Encode screenshots so they can be attached to the LLM request.
import mimetypes  # Infer whether uploaded/Jira files are text files or images.
import os  # Read model and credential settings from environment variables.
from dataclasses import dataclass, field  # Define simple typed containers for incident data.
from pathlib import Path  # Work with local uploaded file paths.
from typing import Iterable  # Accept lists/tuples/generators of attachment paths.

from dotenv import load_dotenv  # Load `.env` values before creating service clients.
from litellm import completion, completion_cost  # Unified LLM calls plus token/cost estimation.

from .integrations import (  # Import service clients and shared data models.
    AttachmentContent,  # Represents text files and screenshots passed to the LLM.
    GitHubRepositoryClient,  # Fetches GitHub file snippets.
    GitLabRepositoryClient,  # Fetches GitLab file snippets.
    JiraClient,  # Fetches Jira issue details and attachments.
    RepositorySnippet,  # Represents numbered source code context.
)
from .preprocessing import ocr_image_file, reduce_log_lines  # Reduce logs and extract screenshot text locally.


SUPPORTED_TEXT_EXTENSIONS = {  # File extensions that should be decoded as prompt text.
    ".txt",  # Plain text logs or notes.
    ".log",  # Application/server log files.
    ".json",  # Structured JSON diagnostic payloads.
    ".xml",  # XML logs/configuration snapshots.
    ".yaml",  # YAML configuration or error artifacts.
    ".yml",  # YAML configuration or error artifacts.
    ".csv",  # Exported tabular evidence.
    ".md",  # Markdown incident notes.
    ".py",  # Python source snippets.
    ".js",  # JavaScript source snippets.
    ".ts",  # TypeScript source snippets.
    ".tsx",  # TSX source snippets.
    ".java",  # Java source snippets.
    ".cs",  # C# source snippets.
    ".go",  # Go source snippets.
    ".rb",  # Ruby source snippets.
    ".php",  # PHP source snippets.
    ".sql",  # SQL scripts or failed queries.
    ".bas",  # VBA/Access source modules.
    ".cls",  # VBA/Access class modules.
}


@dataclass
class IncidentContext:
    """All facts supplied to the LLM for one analysis request."""

    description: str = ""  # Manual issue description entered in the UI/notebook.
    logs: str = ""  # Manual pasted logs or stack traces.
    jira_key: str = ""  # Optional Jira key, such as PROJ-123.
    jira_summary: str = ""  # Jira summary fetched from the issue.
    jira_description: str = ""  # Jira description converted from ADF/plain text.
    jira_comments: list[str] = field(default_factory=list)  # Jira comments from the ticket.
    attachments: list[AttachmentContent] = field(default_factory=list)  # Local/Jira logs and screenshots.
    repository_snippets: list[RepositorySnippet] = field(default_factory=list)  # Focused code snippets.


@dataclass
class TokenUsage:
    """Token and cost metadata returned by LiteLLM."""

    input_tokens: int = 0  # Prompt/input tokens used by the issue package.
    output_tokens: int = 0  # Completion/output tokens generated by the model.
    total_tokens: int = 0  # Combined token total for the request.
    estimated_cost_usd: float = 0.0  # LiteLLM-estimated provider cost in USD.
    model: str = ""  # Model name used for the call.


@dataclass
class IncidentAnalysisResult:
    """Text analysis plus token/cost metadata for the UI."""

    analysis: str = ""  # LLM-generated incident analysis text.
    usage: TokenUsage = field(default_factory=TokenUsage)  # Token and cost details.


class IncidentAnalyzer:
    """Coordinates optional Jira/repository enrichment and LLM analysis."""

    def __init__(self, model: str | None = None):
        load_dotenv()  # Make `.env` credentials available to this process.
        configured_model = model or os.getenv("LITELLM_MODEL") or os.getenv("OPENAI_MODEL") or "openai/gpt-5-nano"
        self.model = normalize_litellm_model(configured_model)  # LiteLLM model string, e.g. openai/gpt-5-nano.

    def analyze(self, context: IncidentContext) -> IncidentAnalysisResult:
        messages = self.build_messages(context)  # Convert gathered evidence into OpenAI chat messages.
        response = completion(  # Send the incident package through LiteLLM's unified SDK.
            model=self.model,  # Use the configured model for the analysis.
            messages=messages,  # Send the grounded developer + user prompt.
        )
        usage = extract_token_usage(response, self.model)  # Pull token/cost details for the UI.
        analysis = response.choices[0].message.content or ""  # Read the assistant text from OpenAI-compatible response.
        return IncidentAnalysisResult(analysis=analysis, usage=usage)  # Return text and usage together.

    def build_messages(self, context: IncidentContext) -> list[dict]:
        user_content: list[dict] = [{"type": "text", "text": build_prompt(context)}]  # Start with the text prompt.

        for attachment in context.attachments:  # Add each screenshot/image as a multimodal input part.
            if attachment.is_image and attachment.content_base64:  # Only encoded images can be attached.
                user_content.append(  # Append the image after the text context.
                    {
                        "type": "image_url",  # OpenAI chat accepts image data through an image_url part.
                        "image_url": {
                            "url": f"data:{attachment.mime_type};base64,{attachment.content_base64}"  # Inline data URL.
                        },
                    }
                )

        return [  # Return the complete message list for the chat completion call.
            {
                "role": "developer",  # Developer message controls behavior and output discipline.
                "content": (
                    "You are a technical issue analysis assistant. Use only the "
                    "facts explicitly provided from the incident, Jira ticket, "
                    "attachments, logs, and repository snippets. Do not invent "
                    "implementation details. If the evidence is insufficient, ask "
                    "targeted clarifying questions before recommending changes. "
                    "When code snippets include line numbers, tie recommendations "
                    "to specific files and lines where possible. Include QA "
                    "guidelines that explain regression, negative, integration, "
                    "and deployment checks for the recommended fix."
                ),
            },
            {"role": "user", "content": user_content},  # Send text plus optional images as the user message.
        ]


def build_prompt(context: IncidentContext) -> str:
    text_attachments = [  # Keep readable attachments inside the text prompt.
        attachment  # Current attachment object.
        for attachment in context.attachments  # Inspect all collected local/Jira attachments.
        if attachment.text_content and not attachment.is_image  # Include only decoded text artifacts.
    ]
    image_attachments = [attachment for attachment in context.attachments if attachment.is_image]  # Track images separately.

    sections = [  # Build the final prompt as ordered, labeled text blocks.
        "You are analyzing a software incident. Analyze ONLY the facts below.",
        "If key details are missing or ambiguous, put targeted questions in Clarifications and do not overstate certainty.",
        "Return this exact format:",
        "1. Clarifications",
        "2. Summary",
        "3. Probable Root Causes",
        "4. Recommended Fix",
        "5. Code Lines To Inspect",
        "6. Verification Steps",
        "7. QA Guidelines",
        "",
        "Keep the answer concise and evidence-based.",
        "",
        "############",
        "Manual Incident Description:",
        context.description.strip() or "Not provided.",
        "############",
        "Manual Logs:",
        reduce_log_lines(context.logs.strip()) or "Not provided.",
        "############",
    ]

    if context.jira_key or context.jira_summary or context.jira_description or context.jira_comments:  # Add Jira only when present.
        sections.extend(  # Append Jira fields as another evidence section.
            [
                "Jira Ticket:",
                f"Key: {context.jira_key or 'Not provided.'}",
                f"Summary: {context.jira_summary or 'Not provided.'}",
                "Description:",
                context.jira_description or "Not provided.",
                "Comments:",
                "\n\n".join(context.jira_comments) if context.jira_comments else "No Jira comments found.",
                "############",
            ]
        )

    if text_attachments or image_attachments:  # Add local/Jira attachments when available.
        attachment_sections = []  # Collect one formatted block per attachment.
        for attachment in text_attachments:  # Include decoded logs/text files directly.
            attachment_sections.append(  # Preserve filename, MIME type, and file content.
                f"File: {attachment.filename}\nMIME: {attachment.mime_type}\nContent:\n{attachment.text_content}"
            )
        for attachment in image_attachments:  # Mention each image in text; bytes are attached separately.
            attachment_sections.append(  # Tell the LLM the screenshot is available as visual evidence.
                "\n".join(
                    [
                        f"Image: {attachment.filename}",
                        f"MIME: {attachment.mime_type}",
                        attachment.text_content or "OCR was not usable, so the image is attached for visual inspection.",
                        "The image is attached to this message for visual inspection.",
                    ]
                )
            )
        sections.extend(["Attachments:", "\n\n---\n\n".join(attachment_sections), "############"])  # Append evidence block.

    if context.repository_snippets:  # Add focused source code context when provided.
        snippets = []  # Collect formatted source snippets.
        for snippet in context.repository_snippets:  # Render each fetched file range.
            snippets.append(  # Include source metadata before the numbered code body.
                "\n".join(
                    [
                        f"Provider: {snippet.provider}",
                        f"Repository: {snippet.repository}",
                        f"Ref: {snippet.ref}",
                        f"Path: {snippet.path}",
                        f"Lines: {snippet.start_line}-{snippet.end_line}",
                        "Code:",
                        snippet.content,
                    ]
                )
            )
        sections.extend(["Repository Code Context:", "\n\n---\n\n".join(snippets), "############"])  # Append repo block.

    return "\n".join(sections)  # Convert the ordered blocks into one prompt string.


def normalize_litellm_model(model: str) -> str:
    """Add the OpenAI provider prefix when callers pass a bare OpenAI model."""

    cleaned = (model or "").strip()  # Normalize empty/whitespace model settings.
    if not cleaned:  # Empty values should use the project default.
        return "openai/gpt-5-nano"  # Default LiteLLM model string.
    if "/" in cleaned or cleaned.startswith("azure/"):  # Provider-prefixed models are already LiteLLM-ready.
        return cleaned  # Return configured model unchanged.
    return f"openai/{cleaned}"  # Treat bare model names as OpenAI models for backward compatibility.


def extract_token_usage(response, model: str) -> TokenUsage:
    """Extract input/output token counts and estimated cost from a LiteLLM response."""

    usage = getattr(response, "usage", None) or {}  # LiteLLM responses expose OpenAI-style usage.
    input_tokens = _usage_value(usage, "prompt_tokens")  # Input token count.
    output_tokens = _usage_value(usage, "completion_tokens")  # Output token count.
    total_tokens = _usage_value(usage, "total_tokens") or input_tokens + output_tokens  # Total token count.
    try:  # LiteLLM can estimate cost for known models/providers.
        estimated_cost = float(completion_cost(completion_response=response) or 0.0)  # USD estimate.
    except Exception:  # Unknown/custom models may not have pricing data.
        estimated_cost = 0.0  # Keep UI stable when pricing is unavailable.
    return TokenUsage(  # Package metrics for UI display.
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        total_tokens=total_tokens,
        estimated_cost_usd=estimated_cost,
        model=model,
    )


def _usage_value(usage, key: str) -> int:
    """Read a token usage value from object-style or dict-style usage payloads."""

    if isinstance(usage, dict):  # Some LiteLLM responses expose usage as a dict.
        return int(usage.get(key) or 0)  # Return dict value or zero.
    return int(getattr(usage, key, 0) or 0)  # Return attribute value or zero.


def load_local_attachments(paths: Iterable[str | Path]) -> list[AttachmentContent]:
    attachments: list[AttachmentContent] = []  # Accumulate readable upload objects.
    for raw_path in paths:  # Process each path received from Gradio or Python caller.
        if not raw_path:  # Ignore empty path values.
            continue
        path = Path(raw_path)  # Normalize the path into a pathlib object.
        if not path.exists() or not path.is_file():  # Skip missing paths and directories.
            continue

        mime_type = mimetypes.guess_type(path.name)[0] or "application/octet-stream"  # Infer MIME from filename.
        suffix = path.suffix.lower()  # Use suffix as a fallback for text-like files.
        is_image = mime_type.startswith("image/")  # Route screenshots to image handling.

        if is_image:  # Try free OCR before sending image bytes to the paid LLM.
            ocr_result = ocr_image_file(path)  # Run local Tesseract OCR against the uploaded screenshot.
            if ocr_result.usable:  # Clear OCR text is cheaper than passing the whole screenshot.
                attachments.append(  # Store OCR text as a normal text attachment.
                    AttachmentContent(
                        filename=f"{path.name} (OCR text)",  # Show that text came from the screenshot.
                        mime_type="text/plain",  # Treat extracted OCR as plain text.
                        text_content=f"[OCR confidence={ocr_result.confidence}]\n{ocr_result.text}",  # Include OCR detail.
                    )
                )
            else:  # Unclear OCR still needs the image-capable model to inspect it.
                content_base64 = base64.b64encode(path.read_bytes()).decode("ascii")  # Convert bytes to ASCII base64.
                attachments.append(  # Store the image attachment metadata and bytes.
                    AttachmentContent(
                        filename=path.name,  # Keep the original filename visible in the prompt.
                        mime_type=mime_type,  # Preserve MIME type for the data URL.
                        content_base64=content_base64,  # Store encoded image bytes.
                        is_image=True,  # Mark as image so build_messages attaches it.
                        text_content=f"OCR fallback reason: {ocr_result.reason}",  # Explain why image was attached.
                    )
                )
        elif suffix in SUPPORTED_TEXT_EXTENSIONS or mime_type.startswith("text/"):  # Decode text/log artifacts.
            attachments.append(  # Store the decoded text attachment.
                AttachmentContent(
                    filename=path.name,  # Keep file identity in the final prompt.
                    mime_type=mime_type,  # Keep MIME metadata for the LLM.
                    text_content=reduce_log_lines(path.read_text(encoding="utf-8", errors="replace")),  # Decode and cap safely.
                )
            )

    return attachments  # Return only files the analyzer can use.


def analyze_incident(
    incident_desc: str,
    error_logs: str,
    jira_key: str = "",
    local_attachment_paths: Iterable[str | Path] | None = None,
    repository_provider: str = "",
    repository: str = "",
    file_path: str = "",
    ref: str = "main",
    start_line: int | None = None,
    end_line: int | None = None,
    include_jira: bool = True,
    include_repository: bool = True,
    model: str | None = None,
) -> IncidentAnalysisResult:
    """Convenience function used by notebooks and Gradio."""

    context = IncidentContext(description=incident_desc, logs=error_logs, jira_key=jira_key)  # Seed manual context.

    # Jira enrichment is optional because many investigations start with only
    # pasted error details and uploaded evidence.
    if include_jira and jira_key:
        jira_ticket = JiraClient.from_env().fetch_ticket(jira_key)  # Fetch issue data using env credentials.
        context.jira_summary = jira_ticket.summary  # Copy the Jira summary into the prompt context.
        context.jira_description = jira_ticket.description  # Copy the Jira description into the prompt context.
        context.jira_comments = jira_ticket.comments  # Copy Jira comments into the prompt context.
        context.attachments.extend(jira_ticket.attachments)  # Add Jira attachments to evidence.

    # Local uploads are always allowed: they support manual log files and
    # screenshots even when Jira/repository integrations are disabled.
    if local_attachment_paths:
        context.attachments.extend(load_local_attachments(local_attachment_paths))  # Add uploaded files/screenshots.

    # Repository enrichment stays focused on a single file/range so the LLM gets
    # useful context without flooding the prompt with unrelated code.
    if include_repository and repository_provider and repository and file_path:
        provider = repository_provider.strip().lower()  # Normalize the provider selection.
        if provider == "github":  # Use GitHub REST API for GitHub repositories.
            repo_client = GitHubRepositoryClient.from_env()  # Build GitHub client from env token/API URL.
        elif provider == "gitlab":  # Use GitLab REST API for GitLab repositories.
            repo_client = GitLabRepositoryClient.from_env()  # Build GitLab client from env token/API URL.
        else:
            raise ValueError("repository_provider must be 'github' or 'gitlab'.")  # Guard unsupported values.

        context.repository_snippets.append(  # Add the fetched code range to the prompt context.
            repo_client.fetch_file_snippet(
                repository=repository,  # Repository identifier, e.g. owner/repo or group/project.
                path=file_path,  # Source file path inside the repository.
                ref=ref or "main",  # Branch, tag, or commit to inspect.
                start_line=start_line,  # Optional focus line start.
                end_line=end_line,  # Optional focus line end.
            )
        )

    return IncidentAnalyzer(model=model).analyze(context)  # Run the final LLM analysis.
